version: 2
updates:
  - package-ecosystem: pip
    directory: /_build
    schedule:
      interval: daily
    labels:
      - dependabot-deps-updates
    allow:
      - dependency-type: all
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "skip-changelog"
